"""Initial Calibrator tables

Revision ID: a8773aa9c50e
Revises: 
Create Date: 2026-09-27 09:19:26.025914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8773aa9c50e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibrator_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('building_type', sa.String(length=100), nullable=True),
    sa.Column('climate_zone', sa.String(length=20), nullable=True),
    sa.Column('prototype_archetype', sa.String(length=100), nullable=True),
    sa.Column('baseline_kwh', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('proposed_kwh', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('annual_savings_kwh', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('annual_savings_dollars', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('comfort_unmet_hours_baseline', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('comfort_unmet_hours_proposed', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('equipment_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coating_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('simulation_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('simulation_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibrator_jobs_job_id'), 'calibrator_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_calibrator_jobs_status'), 'calibrator_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calibrator_jobs_status'), table_name='calibrator_jobs')
    op.drop_index(op.f('ix_calibrator_jobs_job_id'), table_name='calibrator_jobs')
    op.drop_table('calibrator_jobs')
    # ### end Alembic commands ###
