"""Add configuration to calibrator_jobs

Revision ID: feb1efd32be0
Revises: a8773aa9c50e
Create Date: 2026-09-27 10:45:33.888693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'feb1efd32be0'
down_revision: Union[str, None] = 'a8773aa9c50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrator_jobs', sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calibrator_jobs', 'configuration')
    # ### end Alembic commands ###
